### ISSUE TITLE
[keycloak] group team-a not found

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/kubriX#1069]
When enabling crossplane resource health checks in ArgoCD we see a resource degraded:

Reason: hardcoded team-a in templates although team-a is probably not created because not defined in values, see https://github.com/suxess-it/kubriX/blob/9e637b62f9812b05e0adb681161cb85fd1574844/platform-apps/charts/keycloak/templates/cp-keycloak-grafana-group-roles.yaml#L85

Error:

In https://github.com/suxess-it/kubriX/actions/runs/13359794307/job/37307620527?pr=1055

```
 - group: group.keycloak.crossplane.io
    health:
      message: 'cannot resolve references: mg.Spec.ForProvider.GroupID: cannot get
        referenced resource: Group.group.keycloak.crossplane.io "team-a" not found'
      status: Degraded
    kind: Roles
    name: grafana-grafana-group-roles-viewer-team-a
    status: Synced
    syncWave: 1
    version: v1alpha1
```
