### ISSUE TITLE
[keycloak] crossplane resource „ Client pgadmin already exists“

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/kubriX#1084]
https://github.com/suxess-it/kubriX/actions/runs/13508379505/job/37743158985?pr=1055

Why is this a problem for crossplane? An existing resource should be fine in a reconciliation loop, right?

```
 - group: openidclient.keycloak.crossplane.io
    health:
      message: 'create failed: async create failed: failed to create the resource:
        [{0 error sending POST request to /admin/realms/kubrix/clients: 409 Conflict.
        Response body: {"errorMessage":"Client pgadmin already exists"}  []}]'
      status: Degraded
    kind: Client
    name: pgadmin
    status: Synced
    syncWave: 1
    version: v1alpha1
```
