### ISSUE TITLE
[team-onboarding] argocd namespace gets tracking annotation for team-onboarding chart

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/kubriX#1085]
... means that with deleting team-onboarding chart, also argocd namespace gets deleted, which is not what we would expect

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/tracking-id: sx-team-onboarding:app/Namespace:team-onboarding/team-onboarding
  labels:
    kubernetes.io/metadata.name: argocd
    name: argocd
  name: argocd
```
