### ISSUE TITLE
Crossplane vault - group already exists

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/kubriX#1204]
https://github.com/suxess-it/kubriX/actions/runs/14495940555/job/40663668988

```
  - group: identity.vault.upbound.io
    health:
      message: 'create failed: async create failed: failed to create the resource:
        [{0 failed to create identity group "users", reason=group already exists with
        path="/identity/group/name/users", id="01713e17-1ed3-4a77-08c2-ad48f5c9f111"  []}]'
      status: Degraded
    kind: Group
    name: users
    status: Synced
    syncWave: 5
    version: v1alpha1
```
