### ISSUE TITLE
argo-rollouts outofsync in argocd >= 3.0

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/kubriX#1296]
due to https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.14-3.0/#removing-default-ignores-of-preserveunknownfields-for-crd  we needed to add ignoreDifferences to argo-rollouts. Since this is defined in every customer target-chart values, customers need to add this `ignoreDifferences` attribute whereevery they install argo-rollouts to prevent argo-rollouts from being outofsync.

```
- name: argo-rollouts
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
```

With https://github.com/argoproj/argo-rollouts/issues/1272 this will be fixed directly in argo-rollouts (planned for version 1.8).
