### ISSUE TITLE
[grafana] prune datasources

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/kubriX#855]
grafana datasources are searched via sidecar via config https://github.com/grafana/helm-charts/blob/aa5f26297b7d61eb2f8bd29dff938f293ea86dee/charts/grafana/values.yaml#L1048

however, deleted datasource secrets doesn't mean they get pruned in grafana. Is their an additional config needed or is this a missing feature?

**Comment by jkleinlercher** [comment]
This seems to be the solution but a little bit weird (imperative vs descriptive) to list datasources which should get deleted

https://github.com/grafana/helm-charts/issues/898

**Comment by jkleinlercher** [comment]
test scenario proves that datasources with "prune: true" do not get deployed (or are immediately deleted) although they should only get marked for deletion when they are removed from config. see https://github.com/grafana/grafana/issues/94645#issuecomment-2428534214

DataSource:

```
apiVersion: v1
data:
  datasource.yaml: |-
    prune: true
    apiVersion: 1
    datasources:
    - name: datasource-prune-test-jokl2
      type: prometheus
      typeName: prometheus
      uid: datasource-prune-test-jokl2
      basicAuth: false
      url: http://sx-mimir-nginx.mimir.svc:80/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: "POST"
        prometheusType: "Mimir"
        prometheusVersion: "2.9.1"
kind: ConfigMap
metadata:
  annotations:
  labels:
    grafana_datasource: "1"
  name: sx-datasource-prune-test-jokl
  namespace: mimir
````

Logs:


```
logger=provisioning.datasources t=2024-11-26T14:24:37.036339992Z level=info msg="inserting datasource from configuration" name=datasource-prune-test-jokl2 uid=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:24:37.046103626Z level=debug msg="secret value inserted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:24:43.898270424Z level=debug msg="secret value deleted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=provisioning.datasources t=2024-11-26T14:24:43.90547255Z level=info msg="deleted datasource based on configuration" name=datasource-prune-test-jokl2
logger=provisioning.datasources t=2024-11-26T14:25:27.959863574Z level=info msg="inserting datasource from configuration" name=datasource-prune-test-jokl2 uid=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:25:27.971189992Z level=debug msg="secret value inserted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=secrets.kvstore t=2024-11-26T14:25:28.018526559Z level=debug msg="secret value deleted" orgId=1 type=datasource namespace=datasource-prune-test-jokl2
logger=provisioning.datasources t=2024-11-26T14:25:28.028401966Z level=info msg="deleted datasource based on configuration" name=datasource-prune-test-jokl2
````
