### ISSUE TITLE
image scan for changed images in PR

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/kubriX#956]
According to https://snyk.io/de/blog/docker-image-scan-github-action/

make a snyk image scan for every changed image in image-list.md in a PR

1. diff between main branch and PR branch (git diff) for image-list.md
2. for each image (matrix build?) sth like this:

 ```
         - name: Scan Docker image 🐳
             uses: snyk/actions/docker@master
             with:
               image: <<image>>
               args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif
             env:
                SNYK_TOKEN: ${{secrets.SNYK_TOKEN }}
                  
          - name: Upload Snyk report as sarif 📦
             uses: github/codeql-action/upload-sarif@v2
             with:
                sarif_file: snyk.sarif
```

mir trivy:

```
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

```
