### ISSUE TITLE
[vault] secretv2 kv - atProvider missing, unexpected end of JSON input

### ISSUE THREAD

**Issue by phac008** [suxess-it/kubriX#978]
after upgrade provider-vault to v2.0.1

status seems to change from time to time, vault entries are valid, so no direct impact here
....

 
```
 status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2025-01-10T15:54:06Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-01-10T15:55:10Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-01-10T15:55:10Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
```
    
...

```
status:
  atProvider:
    customMetadata:
    - casRequired: false
      data:
        bar: "12345"
        foo: vault@example.com
      deleteVersionAfter: 0
      maxVersions: 5
    deleteAllVersions: true
    disableRead: false
    id: sx-cnp-oss-kv/data/demo/minio
    metadata:
      created_time: "2025-01-10T15:55:10.296671256Z"
      custom_metadata: '{"bar":"12345","foo":"vault@example.com"}'
      deletion_time: ""
      destroyed: "false"
      version: "1"
    mount: sx-cnp-oss-kv
    name: demo/minio
    path: sx-cnp-oss-kv/data/demo/minio
  conditions:
  - lastTransitionTime: "2025-01-10T15:56:10Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-01-10T15:56:10Z"
    message: 'update failed: async update failed: failed to update the resource: [{0
      data_json "" syntax error: unexpected end of JSON input  []}]'
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2025-01-10T15:56:10Z"
    message: 'async update failed: failed to update the resource: [{0 data_json ""
      syntax error: unexpected end of JSON input  []}]'
    reason: AsyncUpdateFailure
    status: "False"
    type: LastAsyncOperation
```
